name: Locust Performance Test

on:
  workflow_dispatch: # Only manual triggering of the workflow
    inputs:
      TEST_DURATION:
        description: "Duration of test (e.g., 10m for 10 minutes)"
        required: true
        default: "10m" # Default duration
      USERS:
        description: "Number of concurrent users"
        required: true
        default: "10" # Default number of users

jobs:
  run-locust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install locust

      - name: Run Locust Load Test
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          TEST_DURATION: ${{ github.event.inputs.TEST_DURATION }} # Duration of test input from user
          USERS: ${{ github.event.inputs.USERS }} # Number of concurrent users input from user

        run: |
          mkdir -p locust-reports 
          locust -f locustfile.py \
          --host $TARGET_URL \
          --users $USERS \
          --run-time $TEST_DURATION \
          --headless \
          --logfile locust_log.log \
          --csv=locust-reports/locust_report \
          --html=locust-reports/locust_report.html

      - name: Upload Locust Logs and Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: locust_reports
          path: locust-reports/
